### ISSUE TITLE
"Validation generated an internal error" - Parsing error with MXF file

### ISSUE THREAD

**Issue by ecodonohoe** [MediaArea/MediaConch#185] opened 2017-06-15 14:35 UTC
I generated a new policy directly from a sample UK DPP AS11 file. ( available for download at ftp://ftp.kw.bbc.co.uk/dppdownload/dpp_example_files)

I then tested the policy with both the original file and 2 separate episodes from a UK DPP AS11 delivery.

All 3 display the red 'X' under the policy heading in the 'Check file' window, seen below:

![mc1](https://user-images.githubusercontent.com/15345230/27184246-870193fc-51d9-11e7-9ea9-492a30f39faf.jpg)

The policy report of the original file checked against its own policy shows a Fail count of 0. (Even with the red 'X'):

![mc2](https://user-images.githubusercontent.com/15345230/27184266-9c7eacd8-51d9-11e7-8266-4376e964e8e5.jpg)

The file for "Feirm 2 Muca agus Caoirigh", displays the expected fails when tested with this policy, but a policy report is produced:

![mc3](https://user-images.githubusercontent.com/15345230/27184386-e878eff4-51d9-11e7-9b52-a53413c0a064.jpg)

The third example, "Feirm 1 Déiríocht", generates an internal error when it tries to produce a policy report:

![mc4](https://user-images.githubusercontent.com/15345230/27184748-f41dbdc0-51da-11e7-9827-ca927b0cfe9f.jpg)

The main questions raised are:

1. Why all three files display the red 'X' under the policy heading, even for the sample file which        displays no fails?
2. Why the particular file for "Feirm 1 Déiríocht" produces an error when another from the same     series will produce a policy report?

Below I've attached the XML(as a text file) for the created policy and the verbose MediaInfo output for "Feirm 1 Déiríocht" in text form.

[xml.txt](https://github.com/MediaArea/MediaConch/files/1077887/xml.txt)

[feirm_ep_1.txt](https://github.com/MediaArea/MediaConch/files/1077867/feirm_ep_1.txt)

Let me know if you need any additional information.
Thanks,

Eoin

**Comment by JeromeMartinez** [comment] 2017-06-15 19:40
"AS11_DPP_HD_EXAMPLE_1": I can reproduce the issue, on our side ( @dericed XML looks OK, maybe on my side, I confirm it soon).
"Feirm 2 Muca agus Caoirigh": I understand the output is the expected result, right?
"Feirm 1 Déiríocht": it is similar to a problem we got in older version of MediaConch. Do you have the latest version of MediaConch (17.05)? please force analyze (reload button in the status colon), maybe you tried this file with an older version of MediaConch containing the bug, and the cache system may have not cleared the old buggy version of the output.

**Comment by ecodonohoe** [comment] 2017-06-16 09:41
Yes "Feirm 2 Muca agus Caoirigh" output is as expected.
I am using the latest version an force analyzing does produce a policy report for "Feirm 1 Déiríocht".

So the slightly revised issues would be:
1. Why the need to force analyze on certain files.
2. Why "AS11_DPP_HD_EXAMPLE_1" displays the red 'X' when it's deemed a pass in the policy report.

**Comment by JeromeMartinez** [comment] 2017-06-16 10:13
> Why the need to force analyze on certain files.

Due to some caching system, in order to not parse again the file just for applying a new policy. For the bug with some MXF files, we chose to not force reanalysis for all files, we definitely need to have a better process when such bug is met. Next version will have a "clear database" option and we plan to have a better versioning system, with a list of impacted caches to clear during an update. In the meanwhile, if you want to get out of this old bug, please open "C:\Users\%USERNAME%\AppData\Roaming\MediaConch and delete MediaConch.db.

> Why "AS11_DPP_HD_EXAMPLE_1" displays the red 'X' when it's deemed a pass in the policy report.

Bug on our side, we work on it.

**Comment by JeromeMartinez** [comment] 2017-06-22 14:10
> Why "AS11_DPP_HD_EXAMPLE_1" displays the red 'X' when it's deemed a pass in the policy report.

Fixed by https://github.com/MediaArea/MediaConch_SourceCode/pull/592.
If you want to test : [Development snapshot](https://mediaarea.net/download/snapshots/binary/mediaconch-gui/).

I think all is fixed, please reopen and comment if it is not the case.

**Closed by JeromeMartinez** 2017-06-22 14:10 UTC
Labels: bug

**Comment by kieranjol** [comment] 2017-06-22 19:12
Thanks Jerome! Hopefully we can test tomorrow.

**Comment by ecodonohoe** [comment] 2017-06-23 10:59
All looks good Jerome. I created a new policy with "Feirm 1 Déiríocht" and compared it against itself, displaying both the green tick and the policy report information:

![m1](https://user-images.githubusercontent.com/15345230/27479020-e4b9c1aa-5809-11e7-9ca7-0f263d044167.jpg)
![mc2](https://user-images.githubusercontent.com/15345230/27479023-e73abea2-5809-11e7-8c85-6d9afd2cdc7d.jpg)

When installing with the latest windows.exe I was prompted that there was a .dll file missing from my computer. (Kieran pointed me to where I could find this.) Is this something that could be included within the .exe file?

![mc](https://user-images.githubusercontent.com/15345230/27479219-e991c1f4-580a-11e7-8176-c8bb4bc3de43.jpg)

**Comment by JeromeMartinez** [comment] 2017-06-23 11:11
> I was prompted that there was a .dll file missing from my computer. (Kieran pointed me to where I could find this.) Is this something that could be included within the .exe file?

There is a potential risk of conflict with Microsoft updates, in addition of not really legal distribution (it is in the grey area about redistribution rights) and it would make our package bigger (different DLL depending of the version of Windows).
We could find a way to detect missing DLLs and check OS version then download the package, but it more work for us, and as far as I know, up to date (service packs, security updates) systems already include these files, so it would be for very few people, it may not worth it (development cost vs usefulness).

Is your OS up to date with service packs and security updates?

**Comment by ecodonohoe** [comment] 2017-06-23 13:51
Yes, it's all up to date now, including that DLL file, and everything is working fine. Thanks for your help.

**Comment by kieranjol** [comment] 2017-06-23 16:18
Jerome is the greatest. Thank you!!!

**Comment by kieranjol** [comment] 2017-06-23 16:20
And tribouille of course!
